export const SEQUELIZE = 'SEQUELIZE';
export const DEVELOPMENT = 'DEVELOPMENT';
export const TEST = 'TEST';
export const PRODUCTION = 'PRODUCTION';
export const USER_REPOSITORY = 'USER_REPOSITORY';
export const POST_REPOSITORY = 'POST_REPOSITORY';
export const CATEGORY_REPOSITORY = 'CATEGORY_REPOSITORY';
export const TAG_REPOSITORY = 'TAG_REPOSITORY';
